version: '3'
services:
  noahbotdb:
    image: mariadb:latest
    env_file:
      - ../docker-data/noahbot/secrets.env
    volumes:
      - ../docker-data/noahbot/noahbot-mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/my.cnf
    labels:
      com.noahbotdb.description: "NoahBot database"
  noahbot:
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - noahbotdb
    env_file:
      - ../docker-data/noahbot/secrets.env
      - ../docker-data/noahbot/channels.env
      - ../docker-data/noahbot/roles.env
    ports:
      - "5000:5000"
    image: noahbot:latest
    labels:
      com.noahbot.description: "NoahBot"
