version: '3'
services:
  noahbot:
    build:
      dockerfile: dockerfile
    env_file:
      - ../docker-data/noahbot/secrets.env
      - ../docker-data/noahbot/channels.env
      - ../docker-data/noahbot/roles.env
    image: noahbot:latest
    network_mode: host
